server {

    listen 80;

    server_name 10.10.60.10 stbubez01.stbu.pl bezsladu.stbu.pl;

    return 301 https://bezsladu.stbu.pl$request_uri;

}

server {

    listen 443 ssl;

    server_name bezsladu.stbu.pl;

    ssl_certificate     /etc/ssl/certs/bezsladu.crt;

    ssl_certificate_key /etc/ssl/private/bezsladu.key;

    client_max_body_size 25M;

    location / {

        proxy_pass http://unix:/opt/bezsladu/bezsladu.sock;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

    }

}