legal_forms:
  - names: ["spółka jawna", "sp. j.", "sp.j.", "sp j"]
  - names: ["spółka partnerska", "sp. p.", "sp.p.", "sp p"]
  - names: ["spółka komandytowa", "sp. k.", "sp.k.", "sp k"]
  - names: ["spółka komandytowo-akcyjna", "S.K.A.", "S.K.A", "SKA", "sp.k.a."]
  - names: ["spółka z ograniczoną odpowiedzialnością", "sp. z o.o.", "sp. z o.o", "sp. z o. o.", "sp. z o. o", "sp. z o.o.", "sp z o.o.", "sp z oo", "sp z o o", "sp z o.o", "sp.z o.o", "sp.z.o.o", "sp.z o.o.", "sp.z.o.o.", "sp. z o o", "SP. Z O. O.", "SP. Z O. O", "SP Z O O", "sp. z o.o."]
  - names: ["prosta spółka akcyjna", "P.S.A.", "P.S.A", "PSA"]
  - names: ["spółka akcyjna", "S.A.", "S.A", "SA"]
  - names: ["zakład usługowo-handlowy", "zakład usługowo handlowy", "zakład produkcyjno-usługowo-handlowy", "zakład produkcyjno-usługowo handlowy", "zakład produkcyjno-handlowy", "zakład produkcyjno handlowy", "zakład handlowy", "zakład usługowy", "przedsiębiorstwo handlowo-usługowe", "przedsiębiorstwo handlowo usługowe", "przedsiębiorstwo produkcyjno-usługowe", "przedsiębiorstwo usługowe", "przedsiębiorstwo produkcyjne", "firma handlowa", "firma usługowa", "firma produkcyjno-usługowa", "firma produkcyjna", "biuro handlowe", "biuro usługowe"]
  - names: ["fundacja", "stowarzyszenie", "TUW", "TUiR"]
