entity_types:
  PERSON: "[OSOBA_{}]"
  ORGANIZATION: "[FIRMA_{}]"
  ADDRESS: "[ADRES_{}]"
  LOCATION: "[LOKALIZACJA_{}]"
  EMAIL_ADDRESS: "[EMAIL_{}]"
  PHONE_NUMBER: "[TELEFON_{}]"
  PL_NIP: "[NIP_{}]"
  PL_KRS: "[KRS_{}]"
  PL_REGON: "[REGON_{}]"
  PL_PESEL: "[PESEL_{}]"
  BANK_ACCOUNT: "[RACHUNEK_{}]"
  LICENSE_PLATE: "[REJESTRACJA_{}]"
  PL_ID_CARD: "[DOWOD_{}]"
  PL_PASSPORT: "[PASZPORT_{}]"
  POLICY_NUMBER: "[POLISA_{}]"
  CLAIM_NUMBER: "[SZKODA_{}]"
